### ISSUE TITLE
Customize AWS Amplify authentication UI for iOS

### ISSUE THREAD

**Issue by edwin0527** [aws-amplify/aws-sdk-ios#1115]
**State your question**
When I use the code in the snippet, the "MyCustomLogo" does not appear and I still see the default logo. However, the background does change to black, but I'm more concern with changing the logo. 

**Which AWS Services are you utilizing?**
AWS Amplify Authentication

**Provide code snippets (if applicable)**

    AWSMobileClient.sharedInstance()
                        .showSignIn(navigationController: self.navigationController!,
                                    signInUIOptions: SignInUIOptions(canCancel: false,
                                                                     logoImage: UIImage(named: "MyCustomLogo"),
                                                                     backgroundColor: UIColor.black)) { (result, err) in
}

**Environment(please complete the following information):**
Latest

I followed the [docs](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html), but still not working. I am pretty new to iOS development so I could be missing something simple but I just can figure out why the logo is not changing.

**Comment by rohandubal** [comment]
Hello @edwin0527 

The "MyCustomLogo" represents putting in an image name part of your app. You need to provide your image input in the `logoImage` argument. Hope this helps.

Thanks,
Rohan

**Comment by edwin0527** [comment]
Thank you, but I understand that part. However, I took an image, named it MyCustomLogo and added it to the project. However, the logo remains with the default and does not display my custom image.

**Comment by muellerfr** [comment]
@rohandubal is working on a fix. Should go out with the next SDK release.

**Comment by rohandubal** [comment]
Hello,

This issue is resolved in `2.7.4` SDK release. Please let us know if you continue to face issues.

Thanks,
Rohan

**Comment by edwin0527** [comment]
Any time frame when 2.7.4 will be released? 2.7.1 is the current release I see now.

**Comment by rohandubal** [comment]
Hello @edwin0527 

To get the latest SDK you will have to run the command `pod install --repo-update` and then `pod update` to make sure your project is using the latest release.

Thanks,
Rohan

**Comment by alenpesikan** [comment]
Ui component is not working well in landscape orientation

**Comment by NickOblec** [comment]
Any updates on this one? I'm still unable to change the logo on the sign-in screen.

**Comment by gabimo** [comment]
> Any updates on this one? I'm still unable to change the logo on the sign-in screen.

I also am waiting for an update on this, doesnt seem to update for OIDC from the console/cognito
