### ISSUE TITLE
Build failure in Xcode 11.5 & 12.0 using AWSMobileClient 2.14.0 with error "use of undeclared type 'AWSServiceConfiguration'"

### ISSUE THREAD

**Issue by corey-plugshare** [aws-amplify/aws-sdk-ios#2818]
**Describe the bug**
Getting the following build failure:

```
aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift:659:39: error: use of undeclared type 'AWSServiceConfiguration'
    let userPoolServiceConfiguration: AWSServiceConfiguration?
```

**To Reproduce**
1. In Xcode 11.5 create a new project
2. Initialize Cocoapods and install the following pods: AWSMobileClient, AWSAuthUI, AWSUserPoolsSignIn
3. Open the project in Xcode using the .xcworkspace file
4. Build

**Observed Behavior**
Build will fail with the following error:

```
aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift:659:39: error: use of undeclared type 'AWSServiceConfiguration'
    let userPoolServiceConfiguration: AWSServiceConfiguration?
```

**Expected Behavior**
A successful build.

**Stack Trace**
```
CompileSwift normal arm64 /Users/coreydavis/Desktop/aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSUserPoolOperationsHandler.swift (in target 'AWSMobileClient' from project 'Pods')
    cd /Users/coreydavis/Desktop/aws-test/Pods
    /Applications/Xcode-11.5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /Users/coreydavis/Desktop/aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift /Users/coreydavis/Desktop/aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClientExtensions.swift /Users/coreydavis/Desktop/aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/Internal/AWSMobileClientUserDetails.swift /Users/coreydavis/Desktop/aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileOptions.swift /Users/coreydavis/Desktop/aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileResults.swift /Users/coreydavis/Desktop/aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/Internal/AWSUserPoolCustomAuthHandler.swift -primary-file /Users/coreydavis/Desktop/aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSUserPoolOperationsHandler.swift /Users/coreydavis/Desktop/aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/DeviceOperations.swift /Users/coreydavis/Desktop/aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/Internal/JSONHelper.swift -emit-module-path /Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/Objects-normal/arm64/AWSUserPoolOperationsHandler\~partial.swiftmodule -emit-module-doc-path /Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/Objects-normal/arm64/AWSUserPoolOperationsHandler\~partial.swiftdoc -emit-module-source-info-path /Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/Objects-normal/arm64/AWSUserPoolOperationsHandler\~partial.swiftsourceinfo -serialize-diagnostics-path /Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/Objects-normal/arm64/AWSUserPoolOperationsHandler.dia -emit-dependencies-path /Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/Objects-normal/arm64/AWSUserPoolOperationsHandler.d -emit-reference-dependencies-path /Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/Objects-normal/arm64/AWSUserPoolOperationsHandler.swiftdeps -target arm64-apple-ios9.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode-11.5.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.5.sdk -I /Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Products/Debug-iphoneos/AWSMobileClient -F /Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Products/Debug-iphoneos/AWSMobileClient -enable-testing -g -import-underlying-module -module-cache-path /Users/coreydavis/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity=checked -Onone -D DEBUG -D COCOAPODS -serialize-debugging-options -Xcc -working-directory -Xcc /Users/coreydavis/Desktop/aws-test/Pods -enable-anonymous-context-mangled-names -Xcc -fmodule-map-file=/Users/coreydavis/Desktop/aws-test/Pods/Headers/Public/AWSAuthCore/AWSAuthCore.modulemap -Xcc -fmodule-map-file=/Users/coreydavis/Desktop/aws-test/Pods/Headers/Public/AWSCognitoIdentityProvider/AWSCognitoIdentityProvider.modulemap -Xcc -fmodule-map-file=/Users/coreydavis/Desktop/aws-test/Pods/Headers/Public/AWSCognitoIdentityProviderASF/AWSCognitoIdentityProviderASF.modulemap -Xcc -fmodule-map-file=/Users/coreydavis/Desktop/aws-test/Pods/Headers/Public/AWSCore/AWSCore.modulemap -Xcc -fmodule-map-file=/Users/coreydavis/Desktop/aws-test/Pods/Headers/Public/AWSMobileClient/AWSMobileClient.modulemap -Xcc -I/Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/AWSMobileClient-generated-files.hmap -Xcc -I/Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/AWSMobileClient-own-target-headers.hmap -Xcc -I/Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/AWSMobileClient-all-target-headers.hmap -Xcc -iquote -Xcc /Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/AWSMobileClient-project-headers.hmap -Xcc -I/Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Products/Debug-iphoneos/AWSMobileClient/include -Xcc -I/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private -Xcc -I/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSMobileClient -Xcc -I/Users/coreydavis/Desktop/aws-test/Pods/Headers/Public -Xcc -I/Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/DerivedSources-normal/arm64 -Xcc -I/Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/DerivedSources/arm64 -Xcc -I/Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -module-name AWSMobileClient -o /Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/AWSMobileClient.build/Objects-normal/arm64/AWSUserPoolOperationsHandler.o -embed-bitcode-marker -index-store-path /Users/coreydavis/Library/Developer/Xcode/DerivedData/aws-test-ghjmeyubqzmpsyevlhtmgwyoogpf/Index/DataStore -index-system-modules

/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSFMDatabasePool.h:177:12: warning: duplicate definition of category 'AWSFMDatabasePoolDelegate' on interface 'NSObject'
@interface NSObject (AWSFMDatabasePoolDelegate)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSFMDatabasePool.h:177:12: note: previous definition is here
@interface NSObject (AWSFMDatabasePoolDelegate)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:72:12: warning: duplicate definition of category 'AWS' on interface 'NSObject'
@interface NSObject (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:72:12: note: previous definition is here
@interface NSObject (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSXMLDictionary.h:105:12: warning: duplicate definition of category 'AWSXMLDictionary' on interface 'NSString'
@interface NSString (AWSXMLDictionary)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSXMLDictionary.h:105:12: note: previous definition is here
@interface NSString (AWSXMLDictionary)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:79:12: warning: duplicate definition of category 'AWS' on interface 'NSString'
@interface NSString (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:79:12: note: previous definition is here
@interface NSString (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSNetworking.h:57:12: warning: duplicate definition of category 'AWSHTTPMethod' on interface 'NSString'
@interface NSString (AWSHTTPMethod)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSNetworking.h:57:12: note: previous definition is here
@interface NSString (AWSHTTPMethod)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSFMDB+AWSHelpers.h:38:12: warning: duplicate definition of category 'AWSHelpers' on interface 'AWSFMDatabasePool'
@interface AWSFMDatabasePool (AWSHelpers)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSFMDB+AWSHelpers.h:38:12: note: previous definition is here
@interface AWSFMDatabasePool (AWSHelpers)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSFMDatabaseAdditions.h:20:12: warning: duplicate definition of category 'AWSFMDatabaseAdditions' on interface 'AWSFMDatabase'
@interface AWSFMDatabase (AWSFMDatabaseAdditions)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSFMDatabaseAdditions.h:20:12: note: previous definition is here
@interface AWSFMDatabase (AWSFMDatabaseAdditions)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSXMLDictionary.h:83:12: warning: duplicate definition of category 'AWSXMLDictionary' on interface 'NSDictionary'
@interface NSDictionary (AWSXMLDictionary)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSXMLDictionary.h:83:12: note: previous definition is here
@interface NSDictionary (AWSXMLDictionary)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:51:12: warning: duplicate definition of category 'AWS' on interface 'NSDictionary'
@interface NSDictionary (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:51:12: note: previous definition is here
@interface NSDictionary (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/NSDictionary+AWSMTLManipulationAdditions.h:11:12: warning: duplicate definition of category 'AWSMTLManipulationAdditions' on interface 'NSDictionary'
@interface NSDictionary (AWSMTLManipulationAdditions)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/NSDictionary+AWSMTLManipulationAdditions.h:11:12: note: previous definition is here
@interface NSDictionary (AWSMTLManipulationAdditions)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/NSArray+AWSMTLManipulationAdditions.h:11:12: warning: duplicate definition of category 'AWSMTLManipulationAdditions' on interface 'NSArray'
@interface NSArray (AWSMTLManipulationAdditions)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/NSArray+AWSMTLManipulationAdditions.h:11:12: note: previous definition is here
@interface NSArray (AWSMTLManipulationAdditions)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:94:12: warning: duplicate definition of category 'AWS' on interface 'NSFileManager'
@interface NSFileManager (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:94:12: note: previous definition is here
@interface NSFileManager (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSMTLModel+NSCoding.h:118:12: warning: duplicate definition of category 'OldArchiveSupport' on interface 'AWSMTLModel'
@interface AWSMTLModel (OldArchiveSupport)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSMTLModel+NSCoding.h:118:12: note: previous definition is here
@interface AWSMTLModel (OldArchiveSupport)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSMTLModel+NSCoding.h:29:12: warning: duplicate definition of category 'NSCoding' on interface 'AWSMTLModel'
@interface AWSMTLModel (NSCoding) <NSCoding>
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSMTLModel+NSCoding.h:29:12: note: previous definition is here
@interface AWSMTLModel (NSCoding) <NSCoding>
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSMTLModel.h:110:12: warning: duplicate definition of category 'Unavailable' on interface 'AWSMTLModel'
@interface AWSMTLModel (Unavailable)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSMTLModel.h:110:12: note: previous definition is here
@interface AWSMTLModel (Unavailable)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSMTLModel.h:94:12: warning: duplicate definition of category 'Validation' on interface 'AWSMTLModel'
@interface AWSMTLModel (Validation)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSMTLModel.h:94:12: note: previous definition is here
@interface AWSMTLModel (Validation)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/AWSMobileClient/AWSAuthSDK/Sources/AWSMobileClient/AWSMobileClient.swift:659:39: error: use of undeclared type 'AWSServiceConfiguration'
    let userPoolServiceConfiguration: AWSServiceConfiguration?
                                      ^~~~~~~~~~~~~~~~~~~~~~~
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:26:12: warning: duplicate definition of category 'AWS' on interface 'NSDate'
@interface NSDate (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:26:12: note: previous definition is here
@interface NSDate (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:66:12: warning: duplicate definition of category 'AWS' on interface 'NSNumber'
@interface NSNumber (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:66:12: note: previous definition is here
@interface NSNumber (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSGZIP.h:38:12: warning: duplicate definition of category 'AWSGZIP' on interface 'NSData'
@interface NSData (AWSGZIP)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSGZIP.h:38:12: note: previous definition is here
@interface NSData (AWSGZIP)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/NSValueTransformer+AWSMTLPredefinedTransformerAdditions.h:81:12: warning: duplicate definition of category 'UnavailableAWSMTLPredefinedTransformerAdditions' on interface 'NSValueTransformer'
@interface NSValueTransformer (UnavailableAWSMTLPredefinedTransformerAdditions)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/NSValueTransformer+AWSMTLPredefinedTransformerAdditions.h:81:12: note: previous definition is here
@interface NSValueTransformer (UnavailableAWSMTLPredefinedTransformerAdditions)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/NSValueTransformer+AWSMTLPredefinedTransformerAdditions.h:25:12: warning: duplicate definition of category 'AWSMTLPredefinedTransformerAdditions' on interface 'NSValueTransformer'
@interface NSValueTransformer (AWSMTLPredefinedTransformerAdditions)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/NSValueTransformer+AWSMTLPredefinedTransformerAdditions.h:25:12: note: previous definition is here
@interface NSValueTransformer (AWSMTLPredefinedTransformerAdditions)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/NSValueTransformer+AWSMTLInversionAdditions.h:11:12: warning: duplicate definition of category 'AWSMTLInversionAdditions' on interface 'NSValueTransformer'
@interface NSValueTransformer (AWSMTLInversionAdditions)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/NSValueTransformer+AWSMTLInversionAdditions.h:11:12: note: previous definition is here
@interface NSValueTransformer (AWSMTLInversionAdditions)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSMTLJSONAdapter.h:167:12: warning: duplicate definition of category 'Deprecated' on interface 'AWSMTLJSONAdapter'
@interface AWSMTLJSONAdapter (Deprecated)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSMTLJSONAdapter.h:167:12: note: previous definition is here
@interface AWSMTLJSONAdapter (Deprecated)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:58:12: warning: duplicate definition of category 'AWS' on interface 'NSJSONSerialization'
@interface NSJSONSerialization (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSCategory.h:58:12: note: previous definition is here
@interface NSJSONSerialization (AWS)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSFMDB+AWSHelpers.h:22:12: warning: duplicate definition of category 'AWSHelpers' on interface 'AWSFMDatabaseQueue'
@interface AWSFMDatabaseQueue (AWSHelpers)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSFMDB+AWSHelpers.h:22:12: note: previous definition is here
@interface AWSFMDatabaseQueue (AWSHelpers)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSUICKeyChainStore.h:246:12: warning: duplicate definition of category 'ForwardCompatibility' on interface 'AWSUICKeyChainStore'
@interface AWSUICKeyChainStore (ForwardCompatibility)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSUICKeyChainStore.h:246:12: note: previous definition is here
@interface AWSUICKeyChainStore (ForwardCompatibility)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSUICKeyChainStore.h:206:12: warning: duplicate definition of category 'ErrorHandling' on interface 'AWSUICKeyChainStore'
@interface AWSUICKeyChainStore (ErrorHandling)
           ^
/Users/coreydavis/Desktop/aws-test/Pods/Headers/Private/AWSCore/AWSUICKeyChainStore.h:206:12: note: previous definition is here
@interface AWSUICKeyChainStore (ErrorHandling)
           ^
```

**Code Snippet**
Not applicable: This happens in a newly created project with no code other than the Xcode boilerplate code.

**Unique Configuration**
Not applicable.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
AWSMobileClient

**Screenshots**
Not applicable.

**Environment(please complete the following information):**
 - SDK Version: 2.14.0
 - Dependency Manager: Cocoapods
 - Swift Version: 5.0
 - Xcode Version: 11.5 & 12.0

**Device Information (please complete the following information):**
 - Device: Simulator
 - iOS Version: iOS 13.5 & 12.0

**Additional context**
Not applicable.

**Relevant Console Output**
Not applicable.

**Comment by corey-plugshare** [comment]
I forgot to mention that it builds successfully on Xcode 11.3.1.

**Comment by royjit** [comment]
I just tried with the Xcode 11.5 and it compiled successfully. Here is my pod file:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AWSMobileClientAuthSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


pod 'AWSMobileClient'
pod 'AWSAuthUI'
pod 'AWSUserPoolsSignIn'

end
```

Could you please retry with a cleaned environment? 
1. Clean the pod cache - `pod cache clean --all` then `pod update`
2. Clean Xcode build folder - `Command-Shift-K`
3. Build the project

**Comment by corey-plugshare** [comment]
@royjit Thanks for posting your Podfile because it pointed me to the problem. The difference between yours and mine is that you use `use_frameworks!` while we are using `use_modual_headers!`. This is an old codebase with both Swift and ObjC, therefore we require the interoperability that `use_modual_headers!` provides. For reasons which I do not understand, everything builds fine with `use_modual_headers!` on Xcode 11.3.1 but fails with 11.5/12.0 only for AWSMobileClient. By opting out of modular headers just for the AWS pods the issue is resolved:

```
    pod 'AWSMobileClient',  :modular_headers => false
    pod 'AWSAuthUI',  :modular_headers => false
    pod 'AWSUserPoolsSignIn',  :modular_headers => false
```

Does anyone know if something changed with Xcode 11.5 that would cause this? I'm happy to have a fix, but am curious about the root cause.

**Comment by aphammyriad** [comment]
I'm also getting this issue using modular headers with a obj C + swift project. Setting :modular_headers => false on the AWS pods doesn't fix it in my case.

**Comment by soueverest** [comment]
Same problem. When I add 'use_framework!' a get another error : https://github.com/facebook/react-native/issues/26405
I'm an error lopping.

**Comment by oleliabo** [comment]
Same here. 

```
  #use_modular_headers!
  pod 'AWSMobileClient'
  pod 'AWSS3'
  pod 'AWSAPIGateway'
```

gives on `pod install`:

```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `AWSMobileClient` depends upon `AWSAuthCore`, `AWSCognitoIdentityProvider`, `AWSCore`, and `AWSCognitoIdentityProviderASF`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

changing to 
```
  pod 'AWSMobileClient', :modular_headers => true
  pod 'AWSAuthCore', :modular_headers => true
  pod 'AWSCognitoIdentityProvider', :modular_headers => true
  pod 'AWSCore', :modular_headers => true
  pod 'AWSCognitoIdentityProviderASF', :modular_headers => true
  pod 'AWSS3',  :modular_headers => true
  pod 'AWSAPIGateway', :modular_headers => true
```

gives on compile: 

```
AWSMobileClient/AWSMobileClient.swift:709:39: error: cannot find type 'AWSServiceConfiguration' in scope
    let userPoolServiceConfiguration: AWSServiceConfiguration?
```

Solution provided in #3358 is not sufficient, since that causes conflict with other libs (react native) that requires static.
