### ISSUE TITLE
Xcode 13.2 support for AWSMobileClientXCF

### ISSUE THREAD

**Issue by alexjameslittle** [aws-amplify/aws-sdk-ios#3981]
When trying to use AWSMobileClient I get the following error. I believe the framework needs to be built with the latest toolchain

```Failed to build module 'AWSMobileClientXCF'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.```

**Comment by royjit** [comment]
Added the latest XCode version to the CircleCI script, this should be fixed in the next release - https://github.com/aws-amplify/aws-sdk-ios/pull/3984

**Comment by royjit** [comment]
This has been released with the version 2.27.1

**Comment by gevartosky** [comment]
I'm having the same issue, but I can't update to 2.27.1 because Amplify uses 2.27.0. What I'm curious to understand is why does it work when importing it via Xcode but not programmatically on a package.swift 😢

**Comment by davedega** [comment]
this error still happening in 2.27.6 running on Xcode 13.3
![image](https://user-images.githubusercontent.com/838391/162263520-7b36728e-1712-4045-b17a-4212323761a5.png)
